[package]
name = "slopcc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
slopcc-common.workspace = true
slopcc-lex.workspace = true
mimalloc.workspace = true
